# Minato est sur le toit
# paralysée d'une façon qui reste a discuter.

m "Shadow... Alors c'est vraiment toi le coupable de tout ce merdier..."
s "Peu importe à présent..."
s "Tout ce qui est fait, ne peut être défait."

# Aveux et explication de chaque cas

m"Shadow... Mais pourquoi tu fais ça ? Dans quel but ?"
s "Pourquoi ? Dans quel but ? Je n'ai pas vraiment de but."
s "Je l'ai fait parce que je pouvais et parce que c'était amusant."
m "Amusant ? De jouer avec des gens ?"
s"Tu ne sais pas quand t'arrêter hein, avec tes questions débiles..."
s"Et d'abord..."
s"Qu'est-ce qui te pousse à aller aussi loin ?"
s"Est-ce que c'est ton sens de la justice ?"
s"Mon cul, ouais..."
s"Je parie que tu voulais juste pimenter ta misérable vie..."
s "En quoi es-tu différent d'un meurtrier qui aime tuer ?"
s "On est pareil tous les deux !"
s "Tu me pourchasses pour rendre ta pitoyable existence excitante !"
m "Non. Je te pourchasse parce que tu blesses mes amis."
s "Et puis tu n'es qu'un étudiant non ?"
s"Tu ne fais que flaner autour de l'école et jouer aux devinettes."
s "Tu as mieux à faire que d'aller fouiner partout..."
s "Tu te crois au club des petits détectives ou quoi ?"
s "Tes études sont plus importantes non ?"
s"Alors travailles bien, trouve une épouse charmante et fonde un foyer."
s"A l'école, joue avec tes amis tant que c'est possible."
m "Ca ne sert à rien de discuter avec toi, des amis, tu n'en as plus."
s"Les amis ? Ca me sert à rien ce truc..."
s "Pourquoi essayer de changer des choses fixées ?"
s "Lloyd est déjà mort, l'associatif aussi."
s "T'as rien de mieux à faire ?"
s "Monsieur le héros solitaire !"
m "Qui est solitaire ici ?"
s "Qu- Quoi ?!"
s "Espèce d'enfoiré arrogant !"
"Il me porte et me lance sur le bord du toit."
"Puis, il s'assoit sur moi, le menton reposant sur une main."
"Il soupire puis me regarde"
s "\"Nous allons attraper le coupable, je vous le promets !!\""
s"Ha ha ha ! C'est si gênant !"
s "J'en ai mal aux côtes !"
m "J'ai juste pitié de toi."
s "Hey ? Les gens naïfs comme toi m'emmerdent !"
s "Leur existence même m'emmerde !!"
s "Je n'ai pas besoin de pauvres merdes comme toi dans mon monde !"
m "Il n'y a pas que ton monde qui existe."
s "Putain... Je pensais que tu comprendrais mais en fait t'es juste trop con !"
"Il se lève et donne de petits coups de pieds pour me pousser vers le bord."
"J'en profite pour faire tomber mon portable discrètement en bas."
"Merde, j'espère que quelqu'un va le voir..."
s"Ha ha ha !! T'as peur ?"
s "Peu importe ce que tu fais, rien ne changera."
s "Tu devrais arrêter pendant qu'il en est encore temps."
s"Tu n'obtiendra rien en affrontant la réalité et impossible de la changer non plus."
s "Alors il vaut mieux l'ignorer et croire que tu vis pleinement ta vie."
s "C'est pas plus facile comme ça ?"
s "Ce serait génial si la vie pouvait être aussi simple."
s "Il n'y a rien d'intéressant dans ce monde terne et ennuyeux."
s "Je n'ai rien à gagner à le préserver."
s"Alors que c'est amusant de jouer avec, puis de le détruire."
s"Mais il n'y a que moi qui joue et c'est tant mieux."
s "Personne ne s'en rend compte."
s "Il sont juste tous coincés parce qu'ils ne peuvent pas nier qu'en fait..."
s "Ceux qui réussissent réellement dans la vie sont ceux qui sont nés avec un ticket magique nommé \"talent\""
s "Ces gens dont un représentant est dressé devant toi."
s "Tu es voué à l'échec."
s "Une fois que tu réalises ça, c'est le désespoir."
s "L'ultime \"GAME OVER\""
s"Donc il vaut mieux ignorer la réalité non ?"
m "La réalité n'est pas un jeu !"
s"..."
s"Je devrais arrêter de parler avec des primates..."
#arrivage


s "Un jour vous verrez."
s "Vous serez confronté à l'ennuyante réalité qui vous confine."
s"Honnêtement, on n'en a pas besoin."
a "Arrete tes conneries !!"
a "Si tu n'acceptes pas la réalité, laisse nous le faire au moins !"
s "Les gosses comme vous sont si naïfs..."
s"Je vois dans vos yeux cette peur de l'avenir..."
s "Vous dissimulez vos angoisses..."
s "Mais ce que je dis est basé sur mes propres expériences !"
s "Je suis devenu insensible à ce monde pitoyable."
s "C'est plutôt agréable en fait..."
s "Etudier, sa marier, travailler, consommer, mourir..."
s "C'est si ennuyeux..."

s"Combien de personne ont déjà réfléchit à la réalité ou à ce qui est bien ou mal ?"
s"Pas grand monde en fait..."
s "Ce monde pourri ne vaut rien et vivre ne sert à rien."
s"La voilà, la vérité que tu as toujours cherché..."
m"Ce n'est pas cette vérité là !"
s "Ola ola, je viens de te dire tout ce qu'il y a à savoir !"
s"C'est cette stupide ignorance que vous appelez espoir qui vous rend tous si ennuyants !"
m"Arrêtes tes conneries !"
m"T'as même pas les couilles de me pousser !"
s "Hein ?"
m "J'en ai marre de t'entendre gémir !"
m"Peu importe ce que tu diras, tu ne t'en tirera pas comme ça !"
m "Tes péchers te suivront toujours !!"
m "La voilà, la vérité !!"
a "Ta logique tordue est celle d'un gamin égoiste et immature !"
a "On ne peut pas vivre seul !"
a "Si tu t'isoles et que tu coupes tes liens avec la société, il deviendra naturellement difficile d'y vivre."
s "Qu'est ce que des sales gosses comme vous en savent ?!"
a "C'est toi le sale gosse !"
a "Affronter la réalité est trop dur pour toi alors tu veux empêcher les autres de le faire ?"
a "Bien sur que personne ne te comprend !"
a "Tu piques une crise comme un enfant perdu !"
s "La ferme !!"
a "Je vais te dire franchement !"
a "Favorisé par le monde, mon cul !"
a "T'es juste un lâche !!"
a "Nous, on se bat pour ce qu'on aime !"
s "Ta gueule ! Ta gueule ! Ta gueule !"
s "Vous... Vous ne devriez pas être aussi confiants !!"
s "A moins de nier en bloc tout ce que je viens de dire !!"
m "Nous avons vu la vérité dans des choses que nous avons toujours refusé de voir."
s"Va te faire foutre !"
s"Un pauvre naïf comme toi ne peut pas comprendre !"
s"As tu seulement une idée de tout ce que j'ai enduré ?!"
m "Shadow, tu n'es pas le seul à souffrir..."
m"Fais face à la vérité !!"

#tombe a genou, hurle puis rit
s"Ha ha ha... Bah quoi... C'est quoi cette merde..."
s"C'est si ennuyant... J'ai... Vraiment perdu..."

